set dotenv-load

# Default recipe to help
default: help

# Print the available recipes
help:
    @just --justfile {{justfile()}} --list

# Install all tutorial dependencies
install:
    poetry install

# Update all tutorial dependencies
update:
    poetry update

# Execute the pre-commit hooks
pre-commit:
    poetry run pre-commit run --all-files

# Run the tutorial
run: pre-commit
    poetry run python -m tutorial2 --model-file=agent_model.json

# Profile the tutorial
profile: pre-commit
    poetry run python -m cProfile -o tutorial2.prof -m tutorial2
    poetry run python -m snakeviz tutorial2.prof
