set dotenv-load

# Default recipe to help
default: help

# Print the available recipes
help:
    @just --justfile {{justfile()}} --list

# Install all tutorial dependencies
install:
    poetry install

# Update all tutorial dependencies
update:
    poetry update

# Run the tutorial
run:
    poetry run python -m taxi_driver_agent