APP_NAME = "Tutorial1 - Self Driving Car"

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 1000
FRAME_RATE = 60

GAME_SEED = 5

VIRTUAL_WIDTH = 500
VIRTUAL_MARGIN = 50

GAMEPAD_ID = 1
GAMEPAD_AXIS_X = 2
GAMEPAD_AXIS_Y = 1
