set dotenv-load

# Default recipe to help
default: help

# Print the available recipes
help:
    @just --justfile {{justfile()}} --list

# Install all tutorial dependencies
install:
    poetry install

# Update all tutorial dependencies
update:
    poetry update

# Build package
build:
    rm -rf dist; poetry build

# Execute the pre-commit hooks
pre-commit:
    poetry run pre-commit run --all-files

# Run the tests
test:
    poetry run coverage run -m pytest -vv

# Run the tutorial
run: pre-commit coverage
    poetry run python -m tutorial1

# Display the coverage report
coverage: test
    poetry run coverage report -m --fail-under=80

# Profile the tutorial
profile: pre-commit coverage
    poetry run python -m cProfile -o tutorial1.prof -m tutorial1
    poetry run python -m snakeviz tutorial1.prof
